# LiipImagineBundle Configuration
liip_imagine:
  resolvers:
    default:
      web_path: ~
  filter_sets:
    avatar:
      quality: 75
      cache: ~
      filters:
        thumbnail: { size: [120, 120], mode: outbound }