vich_uploader:
    db_driver: orm


    mappings:
        user_images:
            uri_prefix: uploads/images
            upload_destination: '%kernel.project_dir%/public/upload/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_files:
            uri_prefix: uploads/fichiers
            upload_destination: '%kernel.project_dir%/public/upload/fichiers/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#        member_image:
#            uri_prefix: uploads/images/member
#            upload_destination: '%kernel.project_dir%/public/uploads/images/member'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#        admin_image:
#            uri_prefix: uploads/images/admin
#            upload_destination: '%kernel.project_dir%/public/uploads/images/admin'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#        coach_files:
#            uri_prefix: uploads/fichiers/coach
#            upload_destination: '%kernel.project_dir%/public/uploads/fichiers/coach'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#        member_files:
#            uri_prefix: uploads/fichiers/member
#            upload_destination: '%kernel.project_dir%/public/uploads/fichiers/member'
#            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
