vich_uploader:
    db_driver: orm



    mappings:
        programme:
            uri_prefix: /images/progromme
            upload_destination: '%kernel.project_dir%/public/images/'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
