#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
      path: /
      controller: App\Controller\DashController::home

#afficheName:
#      path: /AfficheName/{name}
#      controller: App\Controller\StudentController::afficheName