#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homeAdmin:
      path: /Admin
      controller: App\Controller\AdminController::home
homeCoach:
      path: /Coach
      controller: App\Controller\CoachController::home
homeMember:
      path: /Member
      controller: App\Controller\MemberController::home

captcha_routing:
      resource: "@CaptchaBundle/Resources/config/routing.yml"

#afficheName:
#      path: /AfficheName/{name}
#      controller: App\Controller\StudentController::afficheName