<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFDunmFN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFDunmFN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFDunmFN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFDunmFN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFDunmFN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FDunmFN',
    'container.build_id' => '7f773f33',
    'container.build_time' => 1621277277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFDunmFN');
