<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTqvsUTs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTqvsUTs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTqvsUTs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTqvsUTs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTqvsUTs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TqvsUTs',
    'container.build_id' => 'c8fbb97d',
    'container.build_time' => 1617312640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTqvsUTs');
